### PR TITLE
Add a shortlinks Django app.

### PR DESCRIPTION
**Pull request by toolness**
During our latest NYCx meeting we discussed the possibility of using a short URL service like bit.ly to provide branded short URLs, to make links to external resources provided on the textbot take up less precious characters.

Unfortunately, using bit.ly to create URLs with custom domains isn't very cheap (about $40 per month) and they don't have any kind of nonprofit discount.

As an alternative, I figured it shouldn't be too hard to roll-our-own extremely simplistic short URL service as a feature on the tenant platform.  Admins could log into our Django admin backend and use a basic UI to create urls that would be of the form `https://app.justfix.nyc/s/<some short id>`.

Aside from being useful to shorten URLs though, creating a layer of redirection has some other advantages:

* **We have the ability to update where our short URLs point.** This means, for example, if we send a text message that says "go here to learn more about rent reductions" and points to a URL on a government website, it that URL eventually 404's and the user is going through their SMS text history and taps the link, it will 404 too.  However, if the link points to a short URL we've provided, and we change the link's target once it 404's, then tapping that link won't 404 anymore.

* **We can change our external URLs in just one place.** For instance, if we have a single short URL that points to a government page on obtaining rent reductions, and we link to our short URL in our learning center articles and our tenant platform and our text bot, then if the target of that URL ever changes, we can just update the short URL target, instead of having to manually update the content of all our properties.

* **We could regularly sweep through our short URLs and be alerted of any that 404.**  To figure out which links have rotted, we can simply iterate through all the short URLs in our database and regularly check which ones 404.

This adds the feature via a new Django app called `shortlinks`, which Outreach Coordinators have the ability to create and modify.

## Limitations

* This doesn't currently record visits to shortlinks in any way, so we can't easily do metrics (unless we parse our log files, I guess).
* These links aren't _super_ short, e.g. `app.justfix.nyc/s/boop` could be further shortened to something like `jf.nyc/boop`, but that would take more work.
* There's no version history, so it's not easy to revert a change to a shortlink. We could add [django-reversion](https://django-reversion.readthedocs.io/) to get this, though.

### CODE REVIEW

**Comment by toolness** [comment]
[ch7644]

**Comment by toolness** [comment]
Hey @samaratrilling any idea when you might be able to review this?  I think Steph might need its functionality soon-ish for the NYCx work, but I don't think there's an urgent rush.

**Comment by samaratrilling** [comment]
Ah shoot, I missed that I was even on this! So sorry, will do today

**Review by samaratrilling — APPROVED** [review]
This looks good! Might be worth setting the max length of the slug to something a little lower than 200 chars, but that's not a big deal.

So outreach coordinators will be able to edit these on the django admin dashboard?

**Comment by toolness** [comment]
Awesome, thanks!  Yeah, 200 characters is a kind of weird max but I prefer to over-estimate unless there are significant drawbacks to not doing so, but we can always make it shorter later if needed too.

Correct, outreach coordinators will be able to add/edit these.  Come to think of it, though, the "Tenant Resource Editors" group should also probably have access to add/edit these, since these shortlinks are basically used as tenant resources... hmm.  I guess we can always add that permission later, though.

**Pull request merged**
