### PR TITLE
Add support for multiple versions of the EFNY PDF.

### PR DESCRIPTION
**Pull request by toolness**
It looks like there's going to be a new version of the EFNY Hardship Declaration PDF that (hopefully) just changes the date at which protections end.

We can't just simply replace the PDF on our end, because we still need to be able to render old PDFs (ones that were e.g. signed in February) in their original form.  So, this adds a new `pdf_version` attribute to our `HardshipDeclarationVariables` object (which is serialized to the database as JSON) that records what version of the declaration the user signed.

We ensure backwards compatibility by defaulting its value to `1` (the original declaration PDF) when it's not present--this is so that when we pull out legacy `HardshipDeclarationVariables` instances that we are pulling from `SubmittedHardshipDeclaration` models, they are deserialized in a way that represents their true state.

Note that since this only changes the schema of `HardshipDeclarationVariables`--an object that is stored as JSON, not as a database row--this change does not require a database migration (i.e., we're using schema-on-read semantics here).

## To do

- [x] Once we get the new PDF, add it as version `2` and make sure everything works.  Specifically, we want to make sure that all the fields are still in the same place--and if they're not, we need to adjust them in a backwards-compatible way.

### CODE REVIEW

**Comment by toolness** [comment]
Ok @sraby I think this is ready for you to review.  I manually tested it out by visiting an old user on my local dev instance who had already filled out the hardship declaration, clicking the "downloaded completed declaration" link and making sure that it showed me the filled-out old declaration PDF, then signing up as a new user and filling out a new declaration and making sure that they were shown the filled-out new declaration PDF.  I also viewed the new one in Spanish and English to make sure that the fields were filled out properly + in the same place and they appeared to be.

That said, please feel free to double-check all that, as I'm particularly error-prone when it comes to manually testing things.

**Comment by sraby** [comment]
[ch7082]

**Review by sraby — APPROVED** [review]
Awesome, this is great Atul. And really well documented for others (me) to understand.

**Comment by sraby** [comment]
hey @toolness, I removed the "disclaimer" about the "May 1st" deadline on the agree to terms page, and I also updated a few outbound links. This should be good to go.

**Pull request merged**
