### PR TITLE
Add Headroom component to EFNY navbar

### PR DESCRIPTION
**Pull request by sraby**
This PR introduces the react `<Headroom>` component to our Eviction Free NY site, which allows us to implement a special interaction with the navbar on mobile where it automatically hides itself when the user scrolls down but then animates into view when the user scrolls up. 

More details on this custom react component can be found here: https://github.com/KyleAMathews/react-headroom.

### CODE REVIEW

**Comment by sraby** [comment]
[ch6037]

**Review by toolness — APPROVED** [review]
This looks great!  I also tried it in compatibility mode and it looks nice (the actual "scroll up a tiny bit to show the navbar" part is non-functional since that relies on JS, but the user can always scroll to the top of the page to see the navbar so it's not broken or anything).

The one wrinkle I found is that the "Fight to #CancelRent" section at the bottom of the main page appears to overlap the navbar--perhaps it has a conflicting z-index or something?

> image

It also seems like the white text in that section is displayed over the navbar too, it's not just the image.

Anyways it's unfortunate but not a dealbreaker so I'm still going to approve this PR, but if fixing it is quick then you're welcome to do that before merging.

**Comment by sraby** [comment]
thank you @toolness! I'll fix this now

**Comment by sraby** [comment]
thank you @toolness! I'll fix this now

**Pull request merged**
