### PR TITLE
Update content for Eviction Free NY Relaunch

### PR DESCRIPTION
**Pull request by sraby**
This PR adds all the new necessary content that we need to relaunch Eviction Free NY given the moratorium extension to January 2022. Specifically, this PR:
- Adds a new 3rd version of the hardship declaration form PDF that includes updated language from the Office of Court Administration
- Adds a 4th check box to the "Agree to Legal Terms" page of the builder flow that makes sure folks understand landlords can challenge their declaration
- Makes some content changes to the homepage and confirmation pages
- Adds 2 more FAQ questions and updates an existing one

TODO:

- [ ] Swap in Spanish pdf
- [ ] Update HTML for preview content for new Spanish declaration in `declaration-templates/es.tsx`
- [ ] Update coordinates of printed name/signature for SPanish declaration in `hardship_declaration.py`
- [ ] Update url links in HARDSHIP_DECLARATION_FORM_URLS on `homepage.tsx`

### CODE REVIEW

**Review by samaratrilling — APPROVED** [review]
Looks good! Seems like the Spanish version of the PDF is in there - should that be checked off on the PR description? Any of the other ones still open?

**Comment by sraby** [comment]
thank you @samaratrilling! Should've been clearer—`evictionfree/pdf/hardship-declaration-v3-es.pdf` is actually just a duplicate of the English version.

**Comment by samaratrilling** [comment]
Ah, got it. Seems like the other points should be addressed before merging too though, right?

**Comment by sraby** [comment]
@samaratrilling yes definitely

**Pull request merged**
