### PR TITLE
Send "Moratorium Extended" email to existing EFNY users in NY State

### PR DESCRIPTION
**Pull request by sraby**
We want to email EvictionFreeNY users who sent a hardship declaration, notifying them that the eviction moratorium and it's protections have been extended until August 31st.

This is a one-off PR that will likely go unmerged once we actually send the letter. It's based off https://github.com/JustFixNYC/tenants2/pull/2061.

## How to use it:

1. Run `manage.py oneoffemailusers`.  This will generate a file called `oneoffemail.txt` which is just a newline-delimited list of all usernames who we want to send emails to.

2. Run `manage.py sendoneoffemail`.  This will send emails to all the users listed in `oneoffemail.txt`.  It will keep a log of who it's sent emails to so far in `oneoffemail.log`, so if an exception is raised during the sending of an email, you won't have to worry about accidentally double-sending any emails when you re-run the command.

Additionally, you can preview the email at /one-off-email.html on the NoRent site (replace the extension with .txt to see the plaintext version). You can also send a copy of the email to a single user by running manage.py sendoneoffemail --user=<username> (it won't add the username to oneoffemail.log though, nor will it consult that file to see if it's already sent it to that user).

### CODE REVIEW

**Comment by sraby** [comment]
btw @toolness, @samaratrilling and I did the deployment of this together and it was fun. However, I forgot to run the "send emails" command in the background and now it's taking a very very long time...

**Comment by sraby** [comment]
ok the script FINALLY completed all of the email sending! FYI @toolness it's really helpful that the `oneoffemailusers` command generates a list of userIDs that then get sent emails in order. There were a couple of times when the `sendoneoffemail` command got interrupted and stopped because of a network connection issue on my computer, but since we had this list of users in a txt file, and we were logging which emails got sent, all I needed to do was delete previous rows from the list of userIDs who already got sent an email, and then rerun the `sendoneoffemail` command, starting where we left off. 

Anyway, gonna close this PR for now since we are done with the email sending.

**Comment by toolness** [comment]
> There were a couple of times when the `sendoneoffemail` command got interrupted and stopped because of a network connection issue on my computer, but since we had this list of users in a txt file, and we were logging which emails got sent, all I needed to do was delete previous rows from the list of userIDs who already got sent an email, and then rerun the `sendoneoffemail` command, starting where we left off. 

Nice!  I mentioned this to you in-person, but also wanted to mention it here in case anyone else needs to see it again--it looks like I even documented it in the description of #2061 but maybe I didn't do a good enough job (emphasis mine):

> 2. Run `manage.py sendoneoffemail`.  This will send emails to all the users listed in `oneoffemail.txt`.  **It will keep a log of who it's sent emails to so far in `oneoffemail.log`, so if an exception is raised during the sending of an email, you won't have to worry about accidentally double-sending any emails when you re-run the command.**

Hmm, I probably didn't do a good enough job of writing that.  Anyways, the purpose of the log file was to remember who had already been emailed so that they never got double-emailed--the command actually consults that when figuring out who to email next, so you didn't even have to manually edit the text file!

**Comment by toolness** [comment]
Ok I just added the following text to the original description:

> **This also means that if you need to stop the command for any reason, re-running it will pick up right where it left off--i.e., users will never be emailed twice.**

**Pull request closed without merging**
