### PR TITLE
Import assertion helpers from justfix-ts.

### PR DESCRIPTION
**Pull request by samaratrilling**
Fixes issue #1634 .

### CODE REVIEW

**Comment by samaratrilling** [comment]
Seems like maybe we need to change `justfix-ts`'s index.js file to use commonjs syntax instead of ES6? https://stackoverflow.com/questions/38296667/getting-unexpected-token-export

**Comment by samaratrilling** [comment]
Or vice versa, getting our tenants2 to be able to understand es6. something with our babel config?

The problem happens on `yarn build`.

Is this maybe a problem with us having to issue a new version of `justfix-ts`, since I made changes to them recently and this is still loading the old version into `node-modules`?

**Comment by toolness** [comment]
Urg yeah, it looks like some of our TS code that's ultimately being called from the command-line (rather than on the web) doesn't have its funky babel config setup properly.  Lemme take a look...

**Comment by toolness** [comment]
Ok, fixed it in 7072ceaa7e23ca589af5fb09703c2eca627693e9... did not intend for you to have to delve into the semi-hellhole that is our babel/webpack config for this one, sorry about that!

**Review by toolness — APPROVED** [review]
This looks great, thanks @samaratrilling !

**Pull request merged**
