### PR TITLE
Factor out a RentStab type.

### PR DESCRIPTION
**Pull request by toolness**
This is a PR against #1776 that tries to make some of the logic introduced in f3cd6f581a85f866f3e2f1e0eba9768c15095d6b a bit more DRY... it's possibly over-engineered too though, let me know what you think @sraby!  If you like it you can go ahead and merge it into your branch, or just close it without merging.

### CODE REVIEW

**Comment by sraby** [comment]
Wow @toolness I mean I love this, especially the way that it kind of reminds me of our explorations with XState, but also this does seem quite a bit over-engineered, especially given that I don't really see a use for that new structure beyond just this one component. What do you think?

**Comment by toolness** [comment]
Hmm, so ideally I'd say that this [tagged union](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) should just be the actual raw data passed back from the server, obviating the need for transforming it manually on the client-side and having two different rent stab data structures in the codebase.  I didn't think it was possible for GraphQL to represent such a data type, but after doing some googling it looks like it might actually be possible, so let me look into that!

**Comment by toolness** [comment]
Err nevermind, it looks like GraphQL supports unions, but not _tagged_ unions, so there's no easy way to make the server's GraphQL API just use this tagged union natively.  😞 

I guess I'd say I'm preferential to this solution; there's three different places in the code where we're not being DRY by making 3 boolean comparisons, and this obviates that, while also being a more intuitive data structure than what's delivered via GraphQL. It'll also come in handy if we ever need to look at rent stab info from any other part of the codebase too, which we might eventually want to do.

**Comment by toolness** [comment]
Oh, I should also note that this PR does add a tiny bit of new functionality, which is that it automatically just redirects the user to the next step if we can't tell whether they are rent stabilized.  This logic won't be triggered usually, but it could come in handy if e.g. a the `rs-units-check` URL is somewhere in the user's browser history and they navigate back to it at a point that their RS status is unknown (it's a rather pathological edge case but it could happen).

**Comment by sraby** [comment]
Ok cool! In that case, will merge this in!

**Pull request merged**
