### PR TITLE
added dimensions to all staticImage components

### PR DESCRIPTION
**Pull request by sraby**
Fixes issue #840

### CODE REVIEW

**Comment by sraby** [comment]
hey @toolness, I added a required "dimensions" array to the StaticImage component to fix the blinking on Firefox. I came across a frustrating styling conflict that I wasn't able to resolve without redefining the loc image height in sass (see my second commit).

Looks like Bulma globally assigns a height of "auto" to all images, and I can't seem to find a way to permit the html "height" attribute to override this. See here: https://github.com/twbs/bootstrap/issues/1899

Any thoughts on how to make it better?

**Comment by toolness** [comment]
Ah intersting... have you taken a look at Bulma's [Image](https://bulma.io/documentation/elements/image/) documentation?  It seems like they have a bunch of functionality for specifying the aspect ratio of an image, which might actually be the solution we want here, since in some cases we'll want the precise size of our images to vary based on the current viewport size.  Hmmm.

**Comment by sraby** [comment]
Ok, take a look now @toolness! As per your recommendation I made a new Typescript type called BulmaImageClass, which I then added as a subset to the BulmaClassName type. I noticed there wasn't a bulma image ratio wide enough to accommodate the JustFix logo in the header, so I set that ratio as a fixed 128x128 to set the width, and then because the navbar has it's own styling to limit the height, the image comes out at the appropriate scaling. Let me know if you have a better solution for that.

**Comment by sraby** [comment]
cool trick @toolness! was trying to figure out how to do that earlier. Should be ok now

**Pull request merged**
