### PR TITLE
Add session.onboardingScaffolding to GraphQL schema.

### PR DESCRIPTION
**Pull request by toolness**
This moves us closer to #2142 by adding `session.onboardingScaffolding` to the GraphQL schema and deprecating the following fields in favor of it:

* `session.norentScaffolding`
* `session.onboardingStep1`
* `session.onboardingStep3`
* `session.rentalHistoryInfo`

Note that some back-end tests are still referring to some of these deprecated fields.  I didn't change them in part because this PR was becoming a bit larger than I realized and I figured we could also take care of them when we actually remove the deprecated fields (at the very latest).

### CODE REVIEW

**Comment by toolness** [comment]
Hey @samaratrilling this PR is a bit bigger than I realized it'd be... if it's overwhelming, let me know and I can divide it into multiple different PRs (most likely one PR for each field deprecation).

**Comment by samaratrilling** [comment]
Reviewing now! And no worries about the size - seems like most of the files are just renaming `norentScaffolding` => `onboardingScaffolding`

**Review by samaratrilling — COMMENTED** [review]
I am a little confused about where the fields from RentalHistoryInfo went. I don't see them in `session.OnboardingScaffolding` even tho it seems like they should be there. Are the only fields we care about from that object `street` and `aptNumber`?

**Comment by toolness** [comment]
> I am a little confused about where the fields from RentalHistoryInfo went. I don't see them in `session.OnboardingScaffolding` even tho it seems like they should be there. Are the only fields we care about from that object `street` and `aptNumber`?

Oh they are in there, but the reason they aren't called out explicitly in `frontend/lib/rh/routes.tsx` is because they're applied to the rental history form input via [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#description).  `street` and `aptNumber` are dealt with explicitly because they're the only two fields with names that differ between the onboarding scaffolding and the RH form input (`street` is called `address` and `aptNumber` is called `apartmentNumber` in RH form input).

Does that make sense?

**Comment by samaratrilling** [comment]
Oh no I understood the spread syntax - you answered my question (perhaps I should have asked it differently) by explaining that `street` and `aptNumber` are the only two with different key names. Thanks!

**Pull request merged**
